### ISSUE TITLE
Замечания по лабораторной работе

### ISSUE THREAD

**Issue by LikiPiki** [DerFreimensch/OP_LABS#1]
## По коду
1. Нету проверки на NULL, после чтения (см. методичку лабораторная по файлам).
https://github.com/DerFreimensch/OP_LABS/blob/32e0abbb073e6a69c20ca55ae2dbac9c484e5c41/OP_LABS/LAB10_9.c#L67-L68
2. Тут две абсолютно одинаковые проверки на разделитель, которые можно вынести в отдельную функцию и передавать туда только символ для проверки, и возвращать true, false (YES, NO). по результатту проверки. `*(ptr-1)` можно вынести в отдельную переменную.
https://github.com/DerFreimensch/OP_LABS/blob/32e0abbb073e6a69c20ca55ae2dbac9c484e5c41/OP_LABS/LAB10_9.c#L69
https://github.com/DerFreimensch/OP_LABS/blob/32e0abbb073e6a69c20ca55ae2dbac9c484e5c41/OP_LABS/LAB10_9.c#L75
## Вопросы на защиту лабораторной работы:
1. Почему необходимо вызывать функцию free()
2. В чём основные отличия статического двумерного массива от
динамического двумерного массива?
3. Чем ограничивается размер динамического массива?

**Comment by kostr-code** [comment]
1) При динамическом выделении памяти после выполнения программы эта память может не быть очищеной автоматически, поэтому необходимо использовать функцию free(), которая освобождает выделенную память.
2)Возможность изменять количество выделенной для массива памяти. Статический массив - массив на стеке, динамический массив - массив на куче, на стеке создается только указатель на массив, который можно будет создать в куче.
3) Ну тут есть два возможных варианта:
а) Ограничивается объемом ОЗУ
б) Тем количеством памяти, которое выделяется программе
 Думаю, что скорее а
